/**
 * Generates the main workflow.ts execution file.
 * This is the primary output of the compiler -- a standalone TypeScript file
 * that executes the workflow DAG.
 */

import type { ParsedWorkflow, ParsedNode } from '../parser.js';
import type { WorkflowGraph } from '../graph.js';
import { sanitizeNodeName } from '../expression.js';
import { generateIfNode } from './inline/if.js';
import { generateSetNode } from './inline/set.js';
import { generateMergeNode } from './inline/merge.js';
import { generateSwitchNode } from './inline/switch.js';
import { generateCodeNode } from './inline/code.js';
import { generateNoOpNode } from './inline/noop.js';
import { generateFilterNode } from './inline/filter.js';
import { generateShimmedNode, generateShimmedHelper } from './shimmed.js';

export interface GeneratedWorkflow {
  code: string;
  usesShim: boolean;
  nodePackages: Set<string>;
}

/**
 * Generate the complete workflow.ts file content.
 */
export function generateWorkflowCode(
  workflow: ParsedWorkflow,
  graph: WorkflowGraph,
  options: { parallel?: boolean } = {},
): GeneratedWorkflow {
  const parallel = options.parallel ?? true;
  const nodePackages = new Set<string>();
  let usesShim = false;

  // Generate code for each node
  const nodeFunctions: string[] = [];
  for (const nodeName of graph.sortedNodes) {
    const node = workflow.nodes.get(nodeName)!;
    if (node.disabled) continue;

    const code = generateNodeFunction(node);
    nodeFunctions.push(code);

    if (node.compilationMode === 'shimmed') {
      usesShim = true;
      const pkg = getPackageForNode(node.type);
      if (pkg) nodePackages.add(pkg);
    }
  }

  // Build the DAG definition
  const dagDef = generateDagDefinition(workflow, graph);

  // Build the executor invocation
  const executorCode = generateExecutorCode(graph, parallel);

  // Assemble the full file
  const imports = generateImports(usesShim);
  const helpers = generateHelperFunctions();
  const shimHelper = usesShim ? generateShimmedHelper() : '';

  const code = `#!/usr/bin/env npx ts-node
/**
 * Auto-generated workflow: ${workflow.name}
 * Source: ${workflow.id ?? 'local file'}
 * Generated by n8n-to-code
 *
 * DO NOT EDIT the DAG definition or node wiring sections.
 * Node function bodies can be customized.
 */

${imports}
import type { DataItem, NodeOutputMap, ExecutionContext } from '@n8n-to-code/types';

${helpers}

${shimHelper}

// ============================================================
// Node Functions
// ============================================================
${nodeFunctions.join('\n')}

// ============================================================
// DAG Definition
// ============================================================
${dagDef}

// ============================================================
// Workflow Executor
// ============================================================
${executorCode}
`;

  return { code, usesShim, nodePackages };
}

function generateNodeFunction(node: ParsedNode): string {
  switch (node.type) {
    case 'n8n-nodes-base.if':
      return generateIfNode(node);
    case 'n8n-nodes-base.set':
      return generateSetNode(node);
    case 'n8n-nodes-base.merge':
      return generateMergeNode(node);
    case 'n8n-nodes-base.switch':
      return generateSwitchNode(node);
    case 'n8n-nodes-base.code':
      return generateCodeNode(node);
    case 'n8n-nodes-base.noOp':
      return generateNoOpNode(node);
    case 'n8n-nodes-base.filter':
      return generateFilterNode(node);
    case 'n8n-nodes-base.manualTrigger':
      return generateTriggerNode(node);
    default:
      // Check for other trigger types
      if (node.type.includes('Trigger') || node.type.includes('trigger')) {
        return generateTriggerNode(node);
      }
      // All other nodes use shimmed execution
      return generateShimmedNode(node);
  }
}

function generateTriggerNode(node: ParsedNode): string {
  const fnName = `node_${sanitizeNodeName(node.name)}`;

  return `
/**
 * Trigger: ${node.name} (${node.type})
 * Trigger nodes produce the initial data for the workflow.
 * Replace this with actual trigger data or pass it as workflow input.
 */
async function ${fnName}(
  input: DataItem[] | DataItem[][],
  nodeOutputs: NodeOutputMap,
): Promise<DataItem[][]> {
  const items = normalizeInput(input);
  return [items.length > 0 ? items : [{ json: {} }]];
}`;
}

function generateImports(usesShim: boolean): string {
  const lines = [
    `import { DagExecutor } from '@n8n-to-code/executor';`,
    `import { EnvCredentialProvider } from '@n8n-to-code/types';`,
  ];

  if (usesShim) {
    lines.push(`import { ShimExecuteFunctions } from '@n8n-to-code/context-shim';`);
  }

  return lines.join('\n');
}

function generateHelperFunctions(): string {
  return `
// --- Helper: normalize executor input to DataItem[] ---
function normalizeInput(input: DataItem[] | DataItem[][]): DataItem[] {
  return Array.isArray(input[0]) ? (input as DataItem[][]).flat() : (input as DataItem[]);
}

// --- Helper: set nested property ---
function setNestedProperty(obj: Record<string, unknown>, path: string, value: unknown): void {
  const parts = path.split('.');
  let current: Record<string, unknown> = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (!(parts[i] in current) || typeof current[parts[i]] !== 'object') {
      current[parts[i]] = {};
    }
    current = current[parts[i]] as Record<string, unknown>;
  }
  current[parts[parts.length - 1]] = value;
}`;
}

function generateDagDefinition(
  workflow: ParsedWorkflow,
  graph: WorkflowGraph,
): string {
  const nodeEntries: string[] = [];

  for (const nodeName of graph.sortedNodes) {
    const node = workflow.nodes.get(nodeName)!;
    if (node.disabled) continue;

    const fnName = `node_${sanitizeNodeName(nodeName)}`;
    const isMerge = graph.mergeNodes.has(nodeName);
    const isEntry = graph.entryNodes.includes(nodeName);
    const adj = graph.adjacency.get(nodeName) ?? [];

    // Determine outputs count
    const maxOutput = adj.length > 0
      ? Math.max(...adj.map((a) => a.outputIndex)) + 1
      : 1;

    nodeEntries.push(`  '${escapeSingleQuote(nodeName)}': {
    fn: ${fnName},
    isMerge: ${isMerge},
    isEntry: ${isEntry},
    outputCount: ${maxOutput},
  }`);
  }

  // Build edges
  const edgeEntries: string[] = [];
  for (const edge of workflow.edges) {
    const sourceNode = workflow.nodes.get(edge.sourceNode);
    const targetNode = workflow.nodes.get(edge.targetNode);
    if (!sourceNode || sourceNode.disabled || !targetNode || targetNode.disabled) continue;
    if (edge.connectionType !== 'main') continue;

    edgeEntries.push(`  { source: '${escapeSingleQuote(edge.sourceNode)}', sourceOutput: ${edge.sourceOutput}, target: '${escapeSingleQuote(edge.targetNode)}', targetInput: ${edge.targetInput} }`);
  }

  // Build levels
  const levelEntries = graph.levels.map((level) => {
    const activeNodes = level.nodes.filter((n) => {
      const node = workflow.nodes.get(n);
      return node && !node.disabled;
    });
    return `  { level: ${level.level}, nodes: [${activeNodes.map((n) => `'${escapeSingleQuote(n)}'`).join(', ')}] }`;
  });

  return `const workflowDag = {
  nodes: {
${nodeEntries.join(',\n')},
  },
  edges: [
${edgeEntries.join(',\n')},
  ],
  levels: [
${levelEntries.join(',\n')},
  ],
};`;
}

function generateExecutorCode(graph: WorkflowGraph, parallel: boolean): string {
  return `
export async function runWorkflow(
  triggerData: import('@n8n-to-code/types').DataItem[] = [{ json: {} }],
  options: { parallel?: boolean; dataflow?: boolean; credentials?: import('@n8n-to-code/types').ICredentialProvider } = {},
): Promise<NodeOutputMap> {
  const credentials = options.credentials ?? new EnvCredentialProvider();
  const executor = new DagExecutor(workflowDag, {
    parallel: options.parallel ?? ${parallel},
    dataflow: options.dataflow ?? true,
    credentials,
  });
  return executor.run(triggerData);
}

// --- Direct execution ---
if (typeof require !== 'undefined' && require.main === module) {
  runWorkflow()
    .then((outputs) => {
      console.log('Workflow completed. Node outputs:');
      for (const [name, items] of outputs) {
        console.log(\`  \${name}: \${items.length} items\`);
      }
      const entries = [...outputs.entries()];
      const last = entries[entries.length - 1];
      if (last) {
        const [lastNodeName, lastItems] = last;
        console.log(\`\\nFinal output data (\${lastNodeName}):\`);
        lastItems.forEach((item, i) => {
          console.log(JSON.stringify(item.json, null, 2));
        });
      }
    })
    .catch((err) => {
      console.error('Workflow failed:', err);
      process.exit(1);
    });
}`;
}

function escapeSingleQuote(s: string): string {
  return s.replace(/'/g, "\\'");
}

function getPackageForNode(nodeType: string): string | undefined {
  if (nodeType.startsWith('n8n-nodes-base.')) return 'n8n-nodes-base';
  if (nodeType.startsWith('@n8n/n8n-nodes-langchain.')) return '@n8n/n8n-nodes-langchain';
  return nodeType.split('.')[0];
}
