/**
 * DAG Executor: runs a compiled workflow by walking the execution graph.
 * Supports both sequential and parallel execution modes.
 */

import type { DataItem, NodeOutputMap, ICredentialProvider, ILogger } from '@n8n-to-code/types';

/** A node function as generated by the compiler */
export type NodeFunction = (
  input: DataItem[] | DataItem[][],
  nodeOutputs: NodeOutputMap,
  ctx?: ExecutionContext,
) => Promise<DataItem[][]>;

export interface ExecutionContext {
  credentials: ICredentialProvider;
  nodeOutputs: NodeOutputMap;
  logger: ILogger;
  signal?: AbortSignal;
}

export interface DagNode {
  fn: NodeFunction;
  isMerge: boolean;
  isEntry: boolean;
  outputCount: number;
}

export interface DagEdge {
  source: string;
  sourceOutput: number;
  target: string;
  targetInput: number;
}

export interface DagLevel {
  level: number;
  nodes: string[];
}

export interface WorkflowDag {
  nodes: Record<string, DagNode>;
  edges: DagEdge[];
  levels: DagLevel[];
}

export interface DagExecutorOptions {
  /** If true (default), run by level: wait for entire level before next. If false, sequential per level. */
  parallel?: boolean;
  /**
   * If true, use dataflow execution: run a node as soon as all its inputs are ready.
   * This makes Wait nodes in parallel branches cause downstream nodes to run at different times
   * (e.g. different $now timestamps). If false, level-based execution runs all nodes in a level
   * in parallel and waits for the slowest before proceeding.
   */
  dataflow?: boolean;
  credentials?: ICredentialProvider;
  logger?: ILogger;
  signal?: AbortSignal;
}

const defaultLogger: ILogger = {
  debug: (msg: string) => {},
  info: (msg: string) => console.log(`[INFO] ${msg}`),
  warn: (msg: string) => console.warn(`[WARN] ${msg}`),
  error: (msg: string) => console.error(`[ERROR] ${msg}`),
};

/**
 * Execute a compiled workflow DAG.
 */
export class DagExecutor {
  private dag: WorkflowDag;
  private parallel: boolean;
  private dataflow: boolean;
  private credentials: ICredentialProvider;
  private logger: ILogger;
  private signal?: AbortSignal;

  constructor(dag: WorkflowDag, options: DagExecutorOptions = {}) {
    this.dag = dag;
    this.parallel = options.parallel ?? true;
    this.dataflow = options.dataflow ?? false;
    this.credentials = options.credentials ?? { get: async () => ({}) };
    this.logger = options.logger ?? defaultLogger;
    this.signal = options.signal;
  }

  async run(triggerData: DataItem[] = [{ json: {} }]): Promise<NodeOutputMap> {
    const nodeOutputs: NodeOutputMap = new Map();
    const mergeBuffers = new Map<string, MergeBuffer>();

    // Initialize merge buffers
    for (const [name, node] of Object.entries(this.dag.nodes)) {
      if (node.isMerge) {
        const inputCount = this.getInputCount(name);
        mergeBuffers.set(name, new MergeBuffer(inputCount));
      }
    }

    const ctx: ExecutionContext = {
      credentials: this.credentials,
      nodeOutputs,
      logger: this.logger,
      signal: this.signal,
    };

    if (this.dataflow) {
      await this.executeDataflow(triggerData, nodeOutputs, mergeBuffers, ctx);
    } else if (this.parallel) {
      await this.executeParallel(triggerData, nodeOutputs, mergeBuffers, ctx);
    } else {
      await this.executeSequential(triggerData, nodeOutputs, mergeBuffers, ctx);
    }

    return nodeOutputs;
  }

  private async executeSequential(
    triggerData: DataItem[],
    nodeOutputs: NodeOutputMap,
    mergeBuffers: Map<string, MergeBuffer>,
    ctx: ExecutionContext,
  ): Promise<void> {
    for (const level of this.dag.levels) {
      for (const nodeName of level.nodes) {
        if (this.signal?.aborted) throw new Error('Workflow execution cancelled');

        await this.executeNode(nodeName, triggerData, nodeOutputs, mergeBuffers, ctx);
      }
    }
  }

  private async executeParallel(
    triggerData: DataItem[],
    nodeOutputs: NodeOutputMap,
    mergeBuffers: Map<string, MergeBuffer>,
    ctx: ExecutionContext,
  ): Promise<void> {
    for (const level of this.dag.levels) {
      if (this.signal?.aborted) throw new Error('Workflow execution cancelled');

      if (level.nodes.length === 1) {
        // Single node at this level -- no benefit from parallelization
        await this.executeNode(level.nodes[0], triggerData, nodeOutputs, mergeBuffers, ctx);
      } else {
        // Multiple nodes -- execute in parallel
        const results = await Promise.allSettled(
          level.nodes.map((nodeName) =>
            this.executeNode(nodeName, triggerData, nodeOutputs, mergeBuffers, ctx),
          ),
        );

        // Check for failures
        for (let i = 0; i < results.length; i++) {
          const result = results[i];
          if (result.status === 'rejected') {
            this.logger.error(
              `Node "${level.nodes[i]}" failed: ${result.reason}`,
            );
            throw result.reason;
          }
        }
      }
    }
  }

  /**
   * Dataflow execution: run a node as soon as all its inputs are ready.
   * When a node completes we immediately start any downstream that became ready
   * (we do not wait for other nodes in the same "level"), so e.g. Wait0→Edit Fields
   * runs as soon as Wait0 finishes, while Wait2 is still waiting.
   */
  private async executeDataflow(
    triggerData: DataItem[],
    nodeOutputs: NodeOutputMap,
    mergeBuffers: Map<string, MergeBuffer>,
    ctx: ExecutionContext,
  ): Promise<void> {
    const completed = new Set<string>();
    const running = new Set<string>();
    let pendingCount = 0;
    let resolveDone: () => void;
    const done = new Promise<void>((r) => {
      resolveDone = r;
    });

    const getPredecessors = (nodeName: string): string[] => {
      const sources = new Set<string>();
      for (const e of this.dag.edges) {
        if (e.target === nodeName) sources.add(e.source);
      }
      return Array.from(sources);
    };

    const getDownstream = (nodeName: string): string[] => {
      const targets = new Set<string>();
      for (const e of this.dag.edges) {
        if (e.source === nodeName) targets.add(e.target);
      }
      return Array.from(targets);
    };

    const isNodeReady = (nodeName: string): boolean => {
      if (completed.has(nodeName) || running.has(nodeName)) return false;
      const dagNode = this.dag.nodes[nodeName];
      if (!dagNode) return false;
      if (dagNode.isEntry) return true;
      if (dagNode.isMerge) {
        const buf = mergeBuffers.get(nodeName);
        return buf ? buf.isReady() : false;
      }
      const preds = getPredecessors(nodeName);
      return preds.length > 0 && preds.every((p) => completed.has(p));
    };

    const run = (nodeName: string): void => {
      if (completed.has(nodeName) || running.has(nodeName)) return;
      running.add(nodeName);
      pendingCount += 1;
      this.executeNode(nodeName, triggerData, nodeOutputs, mergeBuffers, ctx)
        .then(() => {
          running.delete(nodeName);
          completed.add(nodeName);
          pendingCount -= 1;
          for (const d of getDownstream(nodeName)) {
            if (isNodeReady(d)) run(d);
          }
          if (pendingCount === 0) resolveDone!();
        })
        .catch((err) => {
          running.delete(nodeName);
          pendingCount -= 1;
          this.logger.error(`Node "${nodeName}" failed: ${err}`);
          if (pendingCount === 0) resolveDone!();
          throw err;
        });
    };

    const entryNodes = Object.keys(this.dag.nodes).filter((n) => this.dag.nodes[n].isEntry);
    if (entryNodes.length === 0) return;
    for (const n of entryNodes) run(n);
    await done;
  }

  private async executeNode(
    nodeName: string,
    triggerData: DataItem[],
    nodeOutputs: NodeOutputMap,
    mergeBuffers: Map<string, MergeBuffer>,
    ctx: ExecutionContext,
  ): Promise<void> {
    const dagNode = this.dag.nodes[nodeName];
    if (!dagNode) return;

    this.logger.debug(`Executing node: ${nodeName}`);

    let input: DataItem[] | DataItem[][];

    if (dagNode.isMerge) {
      // Merge node: collect from buffer
      const buffer = mergeBuffers.get(nodeName)!;
      input = buffer.getInputs();
    } else if (dagNode.isEntry) {
      // Entry/trigger node: use trigger data
      input = triggerData;
    } else {
      // Regular node: get input from upstream
      input = this.getNodeInput(nodeName, nodeOutputs);
    }

    // Execute the node function
    const outputs = await dagNode.fn(input, nodeOutputs, ctx);

    // Store the first output as the "main" output for this node
    if (outputs[0]) {
      nodeOutputs.set(nodeName, outputs[0]);
    }

    // Route outputs to downstream nodes
    this.routeOutputs(nodeName, outputs, nodeOutputs, mergeBuffers);
  }

  private routeOutputs(
    nodeName: string,
    outputs: DataItem[][],
    nodeOutputs: NodeOutputMap,
    mergeBuffers: Map<string, MergeBuffer>,
  ): void {
    for (const edge of this.dag.edges) {
      if (edge.source !== nodeName) continue;

      const outputItems = outputs[edge.sourceOutput] ?? [];

      if (mergeBuffers.has(edge.target)) {
        // Target is a merge node: buffer the input
        mergeBuffers.get(edge.target)!.addInput(edge.targetInput, outputItems);
      } else {
        // For regular nodes, the input will be fetched via getNodeInput
        // Store the routed output separately if needed
        const key = `__route:${edge.source}:${edge.sourceOutput}:${edge.target}:${edge.targetInput}`;
        nodeOutputs.set(key, outputItems);
      }
    }
  }

  private getNodeInput(nodeName: string, nodeOutputs: NodeOutputMap): DataItem[] {
    // Find all edges targeting this node
    const incoming = this.dag.edges.filter(
      (e) => e.target === nodeName,
    );

    if (incoming.length === 0) return [];

    // Collect items from all incoming edges
    const items: DataItem[] = [];
    for (const edge of incoming) {
      const routeKey = `__route:${edge.source}:${edge.sourceOutput}:${edge.target}:${edge.targetInput}`;
      const routed = nodeOutputs.get(routeKey);
      if (routed) {
        items.push(...routed);
      } else {
        // Fallback: get from source node's output
        const sourceOutput = nodeOutputs.get(edge.source);
        if (sourceOutput) {
          items.push(...sourceOutput);
        }
      }
    }

    return items;
  }

  private getInputCount(nodeName: string): number {
    const inputIndices = new Set<number>();
    for (const edge of this.dag.edges) {
      if (edge.target === nodeName) {
        inputIndices.add(edge.targetInput);
      }
    }
    return Math.max(inputIndices.size, 1);
  }
}

/**
 * Buffer for merge nodes that need to wait for multiple inputs.
 */
class MergeBuffer {
  private inputs: Map<number, DataItem[]> = new Map();
  private expectedCount: number;

  constructor(expectedCount: number) {
    this.expectedCount = expectedCount;
  }

  addInput(inputIndex: number, items: DataItem[]): void {
    this.inputs.set(inputIndex, items);
  }

  isReady(): boolean {
    return this.inputs.size >= this.expectedCount;
  }

  getInputs(): DataItem[][] {
    const result: DataItem[][] = [];
    for (let i = 0; i < this.expectedCount; i++) {
      result.push(this.inputs.get(i) ?? []);
    }
    return result;
  }
}
